import { afterAll, describe, expect, test } from "bun:test";
import { $ } from "bun";
import { rm } from "fs/promises";
import path from "path";
import { HOOK_TIMEOUT } from "./../setup";

const cacheFile = path.join(
  import.meta.dir,
  "../../.cache/swagger-schemas.json",
);

afterAll(async () => {
  // Clean up the cache file generated by the test so it doesn't affect other tests
  await rm(path.join(import.meta.dir, "../../.cache"), {
    recursive: true,
    force: true,
  });
});

describe("keryx build", () => {
  test(
    "generates swagger schema cache file",
    async () => {
      // Remove any existing cache first
      await rm(path.join(import.meta.dir, "../../.cache"), {
        recursive: true,
        force: true,
      });

      const { stdout, exitCode } = await $`./keryx.ts build`
        .cwd(path.join(import.meta.dir, "../.."))
        .quiet();

      expect(exitCode).toBe(0);
      expect(stdout.toString()).toContain("swagger response schemas");

      // Verify the cache file was created with valid content
      const file = Bun.file(cacheFile);
      expect(await file.exists()).toBe(true);

      const cached = await file.json();
      expect(cached.hash).toMatch(/^[a-f0-9]{64}$/);
      expect(typeof cached.responseSchemas).toBe("object");
      expect(Object.keys(cached.responseSchemas).length).toBeGreaterThan(0);

      // Should contain app-specific actions
      expect(cached.responseSchemas["user:create"]).toBeDefined();
    },
    HOOK_TIMEOUT,
  );

  test(
    "help describes the build command",
    async () => {
      const { stdout, exitCode } = await $`./keryx.ts build --help`
        .cwd(path.join(import.meta.dir, "../.."))
        .quiet();

      expect(exitCode).toBe(0);
      expect(stdout.toString()).toContain("swagger");
    },
    HOOK_TIMEOUT,
  );
});
